package main

import (
	"log"
	"net"

	greetpb "./pb"
	"google.golang.org/grpc"
)

type grpcSrv struct{}

func main() {
	println("Server works!")
	//default gRPC port on localhost
	host := "0.0.0.0:50051"
	//listen to tcp
	lis, err := net.Listen("tcp", host)
	if err != nil {
		log.Fatalf("gRPC server failed: %v", err)
	}
	// create grpc server
	s := grpc.NewServer()
	// register our grpc service and pass grpcServer and out local grpc object
	// the Register method is autogenerated by protoc (see readme file)
	greetpb.RegisterGreetServiceServer(s, &grpcSrv{})
	err = s.Serve(lis)
	if err != nil {
		log.Fatalf("Failed to serve greetpb: %v", err)
	}
}
